[project]
name = "work-fuzzy-guardian"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.guardian-emission-logger]
path = "contracts/guardian-emission-logger.clar"
depends_on = []

[contracts.guardian-incentive-vault]
path = "contracts/guardian-incentive-vault.clar"
depends_on = []

[contracts.guardian-identity-hub]
path = "contracts/guardian-identity-hub.clar"
depends_on = []

[contracts.guardian-validation-oracle]
path = "contracts/guardian-validation-oracle.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
